version: '3'

services:
  postgres:
    image: postgres:14.4
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    expose:
      - 1080
      - 1025

  redis:
    image: redis:7-alpine
    expose:
      - 6379
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    expose:
      - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
      PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10

