version: '3'

services:
  postgres:
    image: postgres:14.4
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    depends_on:
      - postgres

  api:
    image: tuanhung/ecomerce-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
